### ISSUE TITLE
Cool! but where is the rpm?

### ISSUE THREAD

**Issue by tvvocold** [egriffith/Minecraft-Client-RPM#1]

**Comment by egriffith** [comment]
This was mostly just a placeholder while i worked on other projects. The RPM is done I've been meaning to see if RPMFusion will host it. I didn't actually think anyone paid attention to this though o.O I'll make a git repo on my local system and upload it later today.

**Comment by tvvocold** [comment]
Nice! 
Thx!

**Comment by egriffith** [comment]
Sorry about the delay. Github's got a copy of my local system now. If you just want to run the RPM then just download the "Minecraft-(version).rpm." and install it. It should work fine, at least it does here. If you run into any problems let me know. Fedora might complain that the package is unsigned, there's not much I can do about that, but you should be able to override and install anyway. 

 If you want to hack on it and modify it then all the base files are under Sources, I'll eventually push them into a proper RPMBUILD layout when I get the chance.

**Comment by egriffith** [comment]
Sources folder has been placed into a proper rpmbuild structure as I noted above.

**Comment by tvvocold** [comment]
Nice, thx!
